language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install --user pytest # just to be sure
# command to run tests
script:
  - pytest tests.py --verbose # or py.test for Python versions 3.5 and below
